publisher:
  name: Team per la Trasformazione Digitale
  description: |
     Il Team per la Trasformazione Digitale nasce per avviare la costruzione del “sistema operativo” del Paese, una serie di componenti fondamentali sui quali costruire servizi più semplici ed efficaci per i cittadini, la Pubblica amministrazione e le imprese, attraverso prodotti digitali innovativi. La struttura commissariale è stata istituita il 16 settembre 2016 con una scadenza iniziale al 16 settembre 2018. La struttura ha operato in regime di prorogatio fino al 30 ottobre 2018. Il 25 ottobre 2018 è stato nominato dalla Presidenza del Consiglio dei Ministri il nuovo Commissario straordinario per l'attuazione dell'Agenda Digitale. Attualmente il suo decreto, che comprende il rinnovo della struttura, è in fase di registrazione presso la Corte dei Conti.  
    
  github_organization_url: github.com/italia
  short_name: Team Trasf dig
  website: https://teamdigitale.governo.it/
  tags:
    - team
    - digitale
    - trasformazione digitale
  logo: assets/images/logo.svg
